CREATE TABLE `mall_coupon_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned DEFAULT NULL,
  `coupon_code` varchar(48) NOT NULL,
  `name` varchar(120) NOT NULL,
  `coupon_type` varchar(20) NOT NULL,
  `fixed_amount` decimal(12,2) NOT NULL,
  `minimum_cash_amount` decimal(12,2) NOT NULL DEFAULT 0,
  `product_scope_json` json NOT NULL,
  `valid_days` int unsigned NOT NULL DEFAULT 30,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `version` int unsigned NOT NULL DEFAULT 1,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mall_coupon_rule_code` (`tenant_id`, `coupon_code`),
  CONSTRAINT `fk_mall_coupon_rule_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`),
  CONSTRAINT `fk_mall_coupon_rule_shop` FOREIGN KEY (`shop_id`) REFERENCES `shop` (`id`),
  CONSTRAINT `fk_mall_coupon_rule_creator` FOREIGN KEY (`created_by`) REFERENCES `account` (`id`),
  CONSTRAINT `ck_mall_coupon_rule_type` CHECK (`coupon_type` IN ('PRODUCT', 'FREIGHT')),
  CONSTRAINT `ck_mall_coupon_rule_status` CHECK (`status` IN ('ACTIVE', 'INACTIVE')),
  CONSTRAINT `ck_mall_coupon_rule_amount` CHECK (`fixed_amount` > 0),
  CONSTRAINT `ck_mall_coupon_rule_days` CHECK (`valid_days` BETWEEN 1 AND 3650)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SC5 商城现金订单商品券与运费券规则';

CREATE TABLE `member_mall_coupon` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `member_id` bigint unsigned NOT NULL,
  `coupon_rule_id` bigint unsigned NOT NULL,
  `coupon_no` varchar(48) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'AVAILABLE',
  `valid_from` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `valid_until` datetime(3) NOT NULL,
  `locked_order_id` bigint unsigned DEFAULT NULL,
  `version` int unsigned NOT NULL DEFAULT 1,
  `issued_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_member_mall_coupon_no` (`tenant_id`, `coupon_no`),
  KEY `idx_member_mall_coupon_available` (`tenant_id`, `member_id`, `status`, `valid_until`),
  CONSTRAINT `fk_member_mall_coupon_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`),
  CONSTRAINT `fk_member_mall_coupon_member` FOREIGN KEY (`member_id`) REFERENCES `member` (`id`),
  CONSTRAINT `fk_member_mall_coupon_rule` FOREIGN KEY (`coupon_rule_id`) REFERENCES `mall_coupon_rule` (`id`),
  CONSTRAINT `fk_member_mall_coupon_order` FOREIGN KEY (`locked_order_id`) REFERENCES `mall_order` (`id`),
  CONSTRAINT `fk_member_mall_coupon_issuer` FOREIGN KEY (`issued_by`) REFERENCES `account` (`id`),
  CONSTRAINT `ck_member_mall_coupon_status` CHECK (`status` IN ('AVAILABLE', 'LOCKED', 'USED', 'EXPIRED', 'RETURNED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SC5 会员商城券实例';

CREATE TABLE `mall_coupon_ledger` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `tenant_id` bigint unsigned NOT NULL,
  `member_coupon_id` bigint unsigned NOT NULL,
  `mall_order_id` bigint unsigned DEFAULT NULL,
  `action_type` varchar(20) NOT NULL,
  `from_status` varchar(20) DEFAULT NULL,
  `to_status` varchar(20) NOT NULL,
  `business_key` varchar(160) NOT NULL,
  `reason` varchar(255) NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mall_coupon_ledger_business` (`tenant_id`, `business_key`),
  CONSTRAINT `fk_mall_coupon_ledger_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenant` (`id`),
  CONSTRAINT `fk_mall_coupon_ledger_coupon` FOREIGN KEY (`member_coupon_id`) REFERENCES `member_mall_coupon` (`id`),
  CONSTRAINT `fk_mall_coupon_ledger_order` FOREIGN KEY (`mall_order_id`) REFERENCES `mall_order` (`id`),
  CONSTRAINT `fk_mall_coupon_ledger_creator` FOREIGN KEY (`created_by`) REFERENCES `account` (`id`),
  CONSTRAINT `ck_mall_coupon_ledger_action` CHECK (`action_type` IN ('ISSUE', 'LOCK', 'USE', 'RELEASE', 'EXPIRE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SC5 商城券状态流水';
